# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

      # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest

      # Run build of the application
    - name: Run build
      run: go build .

      # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet ./...
        golint ./...

      # Run testing on the code
    - name: Run testing
      run: go test ./... -v
